### ISSUE TITLE
DVGeo does not use original FFD coef values when complex-stepping user functions

### ISSUE THREAD

**Issue by A-CGray** [mdolab/pygeo#135] opened 2022-04-18 19:15 UTC
## Description

When we implement our own functions for span, sweep, chord etc variables, they almost always look something like this:

```python
def span(val, geo):
    C = geo.extractCoef("wing") # Get coeffs for the baseline FFD
    C = f(C, val) # Change the values of C based on val
    geo.restoreCoef(C, "wing") # Set coeffs to new value
```

This form relies on the assumption that every time this function is called, `geo.extractCoef` will return the coefficient values for the baseline FFD configuration. This is true the function is called to update the FFD coordinates, but when DVGeo comes to complex-step over the function,  `geo.extractCoef` instead returns the updated coefficient values.

Effectively then, when DVGeo updates the geometry, it is calling something that behaves like `C_new = f(C_orig, val)` whereas when it does the complex-stepping it is instead calling `f(C_new, val+dh*j)`, a different function.

See https://github.com/mdolab/private-MACH-tutorial/pull/83 for an example of how this can lead to issues.

Most of the time we get away with this because our DV's only add or subtract from coefficients (e.g `C += val`), in which case the derivatives do not depend on C.

### Steps to reproduce issue

1. Put a breakpoint in one of your DVGeo functions
2. Run a script where you run an analysis on a deformed geometry and then compute derivatives
3. Compare the values returned by `geo.extractCoef` when your DVGeo function is called to update the geometry vs when it is called to compute derivatives.

### Current behavior
`geo` object passed to DVGeo functions during complex-stepping process is not the baseline geometry

### Expected behavior
`geo` object passed to DVGeo functions during complex-stepping process should always be the baseline geometry

**Comment by joanibal** [comment] 2022-04-18 22:47
:astonished: Oh no. This seems pretty bad. 

Thanks for letting us know

**Comment by marcomangano** [comment] 2022-04-19 16:24
I assume something is not working as intended [here](https://github.com/mdolab/pygeo/blob/7484ec5a612b2ea64a27da5299d853e9fd0b5457/pygeo/parameterization/DVGeo.py#L1695-L1701), we might have some type inconsistency or wrong conditional that prevent the DVs to be "zeroed" before the new DVs are set

**Comment by marcomangano** [comment] 2022-04-19 16:57
> I assume something is not working as intended [here](https://github.com/mdolab/pygeo/blob/7484ec5a612b2ea64a27da5299d853e9fd0b5457/pygeo/parameterization/DVGeo.py#L1695-L1701), we might have some type inconsistency or wrong conditional that prevent the DVs to be "zeroed" before the new DVs are set

from offline discussion, actually the issue might be that the vars are not reset in [`_update_deriv`](https://github.com/mdolab/pygeo/blob/7484ec5a612b2ea64a27da5299d853e9fd0b5457/pygeo/parameterization/DVGeo.py#L3277-L3286)

**Comment by nwu63** [comment] 2022-06-20 21:06
Does #143 close this issue @joanibal?

**Comment by joanibal** [comment] 2022-06-21 17:22
Yes

**Closed by joanibal** 2022-06-21 17:22 UTC
Labels: bug
